version: "3.8"

volumes:
  mysql-data:
    driver: local

services:

  mysql:
    container_name: laravel-macro-db
    image: mysql:8.0.32
    platform: linux/x86_64
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - mysql-data:/var/lib/mysql

  mailhog:
    container_name: laravel-macro-mailhog
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
      - 1025:1025

  adminer:
    container_name: laravel-macro-adminer
    image: adminer:latest
    ports:
      - 8080:8080

